### ISSUE TITLE
Typo in aggregator command

### ISSUE THREAD

**Issue by valerijvasilcenko** [badoo/liveprof-ui#7]
`/usr/local/bin/php /app/bin/cli.php aggregator:aggregate-manual app label YYYY-MM-DD`
should actually be:
`/usr/local/bin/php /app/bin/cli.php aggregator:aggregate-manual label app  YYYY-MM-DD`
label goes first as it is a required argument

**Comment by shagtv** [comment]
Thanks for your feedback!
I fixed description in wiki
