### ISSUE TITLE
Place aggregator_processor.lock file in custom folder

### ISSUE THREAD

**Issue by droncheg** [badoo/liveprof-ui#8]
Hello! In file `src/Badoo/LiveProfilerUI/ConsoleCommands/ProcessAggregatingJobsCommand.php` at line 31:
`$lock_filename = '/tmp/aggregator_processor.lock';`
Would be great to change hardcoded`/tmp` destination folder by setting it in `src/config/aggregator_services.yaml` config file, or using system/php variables (like TMP, TMPDIR or TEMP). That's important when i need 2 instances of liveprof/liveprof-ui on same host without docker.

Tnx for this usefull tool!

UPD: same in `tests/unit/Badoo/LiveProfilerUI/LoggerTest.php`, but i'm not using it =)

**Comment by shagtv** [comment]
Thanks for the report. Lock name was fixed in 1.2.10. 
In the logger case it's not a problem because of parameter aggregator.log_file in config/services.yaml
